version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.1
      - image: trufflesuite/ganache-cli:v6.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/repo
      - run: npm run test

  code_coverage:
    docker:
      - image: circleci/node:10.1
      - image: trufflesuite/ganache-cli:v6.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/repo
      - run: npm run coverage
      - store_artifacts:
          path: ~/repo/coverage.json
          destination: coverage.json
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage

  lint:
    docker:
      - image: circleci/node:10.1
      - image: trufflesuite/ganache-cli:v6.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - attach_workspace:
          at: ~/repo
      - run: npm run lint

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - test
      - code_coverage
      - lint
